/**
 * 專案 CLAUDE.md 部署 — 寫入 ~/.claude/projects/{org}/{repo}/CLAUDE.md
 *
 * Claude Code 原生支持 ~/.claude/projects/ 目錄，
 * 根據當前工作目錄自動匹配對應的 CLAUDE.md。
 *
 * 目錄結構：
 *   ~/.claude/projects/{org}/{repo}/         ← 實際資料（人類可讀）
 *   ~/.claude/projects/{path-encoded}        ← symlink → {org}/{repo}/（Claude Code 查找用）
 */

import fs from 'node:fs';
import path from 'node:path';
import { encodeProjectPath } from '../config/config-classifier.mjs';
import { HOME } from '../core/paths.mjs';

const PROJECTS_DIR = path.join(HOME, '.claude', 'projects');

const GENERATED_MARKER = '# Generated by ab-tao — DO NOT EDIT manually\n';
const LEGACY_MARKER = '# Generated by ab-dotfiles — DO NOT EDIT manually\n';

/**
 * 建立 org/repo 目錄 + path-encoded symlink
 *
 * @param {string} localPath - 本機路徑（如 /Users/alvin/.../ab-tao）
 * @param {string} repoFullName - org/repo 名（如 AlvinBian/ab-tao）
 * @returns {string} org/repo 目錄的完整路徑
 */
function ensureProjectDir(localPath, repoFullName) {
  const orgRepoPath = path.resolve(PROJECTS_DIR, repoFullName);
  // 防止路徑穿越：確保目標在 PROJECTS_DIR 內
  if (!orgRepoPath.startsWith(PROJECTS_DIR)) return PROJECTS_DIR;
  fs.mkdirSync(orgRepoPath, { recursive: true });

  // symlink：path-encoded → org/repo（Claude Code 用路徑查找）
  const encoded = encodeProjectPath(localPath);
  const encodedPath = path.join(PROJECTS_DIR, encoded);
  if (!fs.existsSync(encodedPath)) {
    try {
      const relTarget = path.relative(PROJECTS_DIR, orgRepoPath);
      fs.symlinkSync(relTarget, encodedPath);
    } catch {
      // Windows 無管理員權限時 symlink 失敗 → fallback 用目錄複製
      if (!fs.existsSync(encodedPath)) {
        fs.mkdirSync(encodedPath, { recursive: true });
      }
    }
  }

  return orgRepoPath;
}

/** 判斷內容是否為自動生成（相容新舊 marker） */
function isGenerated(content) {
  return content.startsWith(GENERATED_MARKER) || content.startsWith(LEGACY_MARKER);
}

/**
 * 部署單個 repo 的 CLAUDE.md
 *
 * 同時寫入兩個位置：
 *   1. ~/.claude/projects/{org}/{repo}/CLAUDE.md — Claude Code 個人專案配置
 *   2. {localPath}/CLAUDE.md                    — repo 根目錄，可 commit 供團隊共用
 *
 * 以 GENERATED_MARKER 判斷是否為自動生成，用戶手寫的不覆蓋。
 *
 * @param {string} localPath - repo 本機路徑
 * @param {string} claudeMdContent - CLAUDE.md 內容
 * @param {string} repoFullName - org/repo 名稱（如 AlvinBian/ab-tao）
 * @returns {{ deployed: boolean, path: string, repoDeployed: boolean, skipped?: string }}
 */
export function deployProjectClaudeMd(localPath, claudeMdContent, repoFullName = '') {
  if (!localPath || !claudeMdContent) {
    return { deployed: false, repoDeployed: false, path: '', skipped: 'no content' };
  }

  // 1. 寫入 ~/.claude/projects/
  let projectDir;
  if (repoFullName) {
    projectDir = ensureProjectDir(localPath, repoFullName);
  } else {
    // fallback：無 repoFullName 時用 path-encoded 格式
    const encoded = encodeProjectPath(localPath);
    projectDir = path.join(PROJECTS_DIR, encoded);
    fs.mkdirSync(projectDir, { recursive: true });
  }
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');

  if (fs.existsSync(claudeMdPath)) {
    const existing = fs.readFileSync(claudeMdPath, 'utf8');
    if (!isGenerated(existing)) {
      return { deployed: false, repoDeployed: false, path: claudeMdPath, skipped: '用戶自訂' };
    }
  }

  fs.mkdirSync(projectDir, { recursive: true });
  fs.writeFileSync(claudeMdPath, GENERATED_MARKER + claudeMdContent);

  // 2. 同步寫入 repo 根目錄（供團隊共用）
  let repoDeployed = false;
  const repoClaude = path.join(localPath, 'CLAUDE.md');
  if (fs.existsSync(localPath)) {
    const repoExisting = fs.existsSync(repoClaude) ? fs.readFileSync(repoClaude, 'utf8') : null;
    if (!repoExisting || isGenerated(repoExisting)) {
      fs.writeFileSync(repoClaude, GENERATED_MARKER + claudeMdContent);
      repoDeployed = true;
    }
  }

  return { deployed: true, repoDeployed, path: claudeMdPath };
}

// ── .claudeignore：掃描 repo 目錄自動偵測，減少 Claude 掃描的 token 消耗 ──

const CLAUDEIGNORE_MARKER = '# Generated by ab-tao';

/**
 * 偵測規則：檢查檔案/目錄是否存在 → 加入對應忽略規則
 * [偵測目標, 忽略規則陣列]
 */
const DETECT_RULES = [
  // Node.js 生態
  ['node_modules', ['node_modules/']],
  ['pnpm-lock.yaml', ['pnpm-lock.yaml']],
  ['package-lock.json', ['package-lock.json']],
  ['yarn.lock', ['yarn.lock']],
  // 構建產物
  ['dist', ['dist/']],
  ['build', ['build/']],
  ['coverage', ['coverage/']],
  ['.cache', ['.cache/']],
  ['.turbo', ['.turbo/']],
  // 框架特定
  ['.next', ['.next/']],
  ['.nuxt', ['.nuxt/', '.output/']],
  ['.output', ['.output/']],
  ['.vite', ['.vite/']],
  // Python
  ['__pycache__', ['__pycache__/', '*.pyc']],
  ['.venv', ['.venv/']],
  ['venv', ['venv/']],
  ['requirements.txt', ['*.pyc', '__pycache__/']],
  ['pyproject.toml', ['*.pyc', '__pycache__/', '.mypy_cache/']],
  // Go
  ['go.mod', ['vendor/']],
  // Rust
  ['Cargo.toml', ['target/']],
  // Flutter / Dart
  ['pubspec.yaml', ['.dart_tool/', 'build/', '.flutter-plugins']],
  // Swift / Xcode
  ['Package.swift', ['.build/', 'DerivedData/']],
  ['*.xcodeproj', ['.build/', 'DerivedData/', '*.xcworkspace/xcuserdata/']],
  // PHP
  ['composer.json', ['vendor/']],
  // Java / Kotlin
  ['build.gradle', ['build/', '.gradle/', 'out/']],
  ['build.gradle.kts', ['build/', '.gradle/', 'out/']],
  ['pom.xml', ['target/']],
  // Ruby
  ['Gemfile', ['vendor/bundle/']],
  // .NET
  ['*.csproj', ['bin/', 'obj/']],
  ['*.sln', ['bin/', 'obj/', 'packages/']],
  // 通用大檔案
  ['.git', ['.git/']],
  ['*.min.js', ['*.min.js']],
  ['*.min.css', ['*.min.css']],
  ['*.map', ['*.map']],
  // 容器 / CI
  ['.terraform', ['.terraform/']],
];

/**
 * 掃描 repo 目錄，偵測實際存在的檔案/目錄，生成 .claudeignore
 *
 * @param {string} localPath - repo 本機路徑
 * @returns {string} .claudeignore 內容
 */
function generateClaudeignore(localPath) {
  const rules = new Set();
  let entries;
  try {
    entries = new Set(fs.readdirSync(localPath));
  } catch {
    return '';
  }

  for (const [detect, ignores] of DETECT_RULES) {
    let matched = false;
    if (detect.includes('*')) {
      // glob 模式：*.csproj → 任何 .csproj 檔案
      const ext = detect.replace('*', '');
      matched = [...entries].some((e) => e.endsWith(ext));
    } else {
      matched = entries.has(detect);
    }
    if (matched) {
      for (const rule of ignores) rules.add(rule);
    }
  }

  if (rules.size === 0) return '';
  return `${CLAUDEIGNORE_MARKER} — 減少 Claude Code 掃描的 token 消耗\n${[...rules].join('\n')}\n`;
}

/**
 * 部署 .claudeignore 到 ~/.claude/projects/{org}/{repo}/
 * 不碰項目目錄，完全在 ~/.claude/ 內完成。
 * 配合 PreToolUse hook 攔截匹配的文件讀取。
 *
 * @param {string} localPath - repo 本機路徑
 * @param {string} [repoFullName] - org/repo 名（如 AlvinBian/ab-tao）
 * @returns {boolean} 是否有寫入
 */
export function deployClaudeignore(localPath, repoFullName) {
  if (!localPath || !fs.existsSync(localPath)) return false;

  const content = generateClaudeignore(localPath);
  if (!content) return false;

  // 部署到 ~/.claude/projects/{org}/{repo}/.claudeignore（不碰項目目錄）
  if (repoFullName) {
    const projectDir = path.resolve(PROJECTS_DIR, repoFullName);
    if (!projectDir.startsWith(PROJECTS_DIR)) return false; // 路徑穿越防護
    fs.mkdirSync(projectDir, { recursive: true });
    const ignorePath = path.join(projectDir, '.claudeignore');
    if (fs.existsSync(ignorePath)) {
      const existing = fs.readFileSync(ignorePath, 'utf8');
      if (!existing.startsWith(CLAUDEIGNORE_MARKER)) return false;
    }
    fs.writeFileSync(ignorePath, content);
  } else {
    // fallback：無 repoFullName 時放 repo 根目錄
    const ignorePath = path.join(localPath, '.claudeignore');
    if (fs.existsSync(ignorePath)) {
      const existing = fs.readFileSync(ignorePath, 'utf8');
      if (!existing.startsWith(CLAUDEIGNORE_MARKER)) return false;
    }
    fs.writeFileSync(ignorePath, content);
  }

  return true;
}

/**
 * 批量部署多個 repo 的 CLAUDE.md + .claudeignore
 *
 * @param {Array<{ localPath: string, content: string, repo: string }>} items
 * @returns {{ deployed: string[], skipped: string[], claudeignoreCount: number }}
 */
export function deployAllProjectClaudeMd(items) {
  const deployed = [];
  const repoDeployed = [];
  const skipped = [];
  let claudeignoreCount = 0;

  for (const { localPath, content, repo } of items) {
    const result = deployProjectClaudeMd(localPath, content, repo);
    if (result.deployed) {
      deployed.push(repo);
      if (result.repoDeployed) repoDeployed.push(repo);
    } else if (result.skipped) {
      skipped.push(`${repo}（${result.skipped}）`);
    }

    // 掃描 repo 目錄自動生成 .claudeignore → ~/.claude/projects/{org}/{repo}/
    if (deployClaudeignore(localPath, repo)) claudeignoreCount++;
  }

  return { deployed, repoDeployed, skipped, claudeignoreCount };
}

/**
 * 為所有有本機路徑的 repos 部署 .claudeignore（獨立於 CLAUDE.md）
 *
 * @param {Array<{ localPath: string, repo: string }>} repos - 有 localPath 的 repo 列表
 * @returns {{ count: number, repos: string[] }}
 */
export function deployAllClaudeignore(repos) {
  const result = [];
  for (const { localPath, repo } of repos) {
    if (deployClaudeignore(localPath, repo)) result.push(repo);
  }
  return { count: result.length, repos: result };
}
