/**
 * 專案 CLAUDE.md 部署 — 寫入 ~/.claude/projects/{path-encoded}/CLAUDE.md
 *
 * Claude Code 原生支持 ~/.claude/projects/ 目錄，
 * 根據當前工作目錄自動匹配對應的 CLAUDE.md。
 */

import fs from 'node:fs';
import path from 'node:path';
import { encodeProjectPath } from '../config/config-classifier.mjs';

const HOME = process.env.HOME;
const PROJECTS_DIR = path.join(HOME, '.claude', 'projects');

const GENERATED_MARKER = '# Generated by ab-dotfiles — DO NOT EDIT manually\n';

/**
 * 部署單個 repo 的 CLAUDE.md
 *
 * 同時寫入兩個位置：
 *   1. ~/.claude/projects/{encoded}/CLAUDE.md — Claude Code 個人專案配置
 *   2. {localPath}/CLAUDE.md                 — repo 根目錄，可 commit 供團隊共用
 *
 * 兩個位置都以 GENERATED_MARKER 判斷是否為自動生成，用戶手寫的不覆蓋。
 *
 * @param {string} localPath - repo 本機路徑
 * @param {string} claudeMdContent - CLAUDE.md 內容
 * @returns {{ deployed: boolean, path: string, repoDeployed: boolean, skipped?: string }}
 */
export function deployProjectClaudeMd(localPath, claudeMdContent) {
  if (!localPath || !claudeMdContent) {
    return {
      deployed: false,
      repoDeployed: false,
      path: '',
      skipped: 'no content',
    };
  }

  // 1. 寫入 ~/.claude/projects/
  const encoded = encodeProjectPath(localPath);
  const projectDir = path.join(PROJECTS_DIR, encoded);
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');

  if (fs.existsSync(claudeMdPath)) {
    const existing = fs.readFileSync(claudeMdPath, 'utf8');
    if (!existing.startsWith(GENERATED_MARKER)) {
      return {
        deployed: false,
        repoDeployed: false,
        path: claudeMdPath,
        skipped: '用戶自訂',
      };
    }
  }

  fs.mkdirSync(projectDir, { recursive: true });
  fs.writeFileSync(claudeMdPath, GENERATED_MARKER + claudeMdContent);

  // 2. 同步寫入 repo 根目錄（供團隊共用）
  let repoDeployed = false;
  const repoClaude = path.join(localPath, 'CLAUDE.md');
  if (fs.existsSync(localPath)) {
    const repoExisting = fs.existsSync(repoClaude) ? fs.readFileSync(repoClaude, 'utf8') : null;
    if (!repoExisting || repoExisting.startsWith(GENERATED_MARKER)) {
      fs.writeFileSync(repoClaude, GENERATED_MARKER + claudeMdContent);
      repoDeployed = true;
    }
  }

  return { deployed: true, repoDeployed, path: claudeMdPath };
}

/**
 * 批量部署多個 repo 的 CLAUDE.md
 *
 * @param {Array<{ localPath: string, content: string, repo: string }>} items
 * @returns {{ deployed: string[], skipped: string[] }}
 */
export function deployAllProjectClaudeMd(items) {
  const deployed = [];
  const repoDeployed = [];
  const skipped = [];

  for (const { localPath, content, repo } of items) {
    const result = deployProjectClaudeMd(localPath, content);
    if (result.deployed) {
      deployed.push(repo);
      if (result.repoDeployed) repoDeployed.push(repo);
    } else if (result.skipped) {
      skipped.push(`${repo}（${result.skipped}）`);
    }
  }

  return { deployed, repoDeployed, skipped };
}
