/**
 * 預索引生成 — 為每個 repo 自動生成壓縮索引
 *
 * 根據 repo 實際存在的文件/目錄結構，生成對應的索引文件到 {repo}/.claude/index/
 * 減少 Claude Code 探索 codebase 的 token 消耗（實測 50K→3K）。
 *
 * 索引文件：
 *   - api-routes.md：API 端點路徑列表
 *   - components.md：組件樹結構
 *   - exports.md：package.json 的 name、scripts、dependencies
 *   - schema.md：Prisma/Drizzle schema 定義
 *   - structure.md：src/ 下兩層目錄結構樹
 */

import fs from "node:fs";
import path from "node:path";
import { isEmpty } from "lodash-es";
import { HOME } from "../core/paths.mjs";

const INDEX_MARKER = "# Generated by ab-tao — repo index\n";

/**
 * 判斷內容是否為自動生成的索引
 *
 * @param {string} content - 檔案內容
 * @returns {boolean}
 */
function isGeneratedIndex(content) {
	return content.startsWith(INDEX_MARKER);
}

/** 跳過的目錄（避免掃描大型依賴/產出目錄） */
const SKIP_DIRS = new Set([
	"node_modules",
	".git",
	"dist",
	"build",
	".next",
	".nuxt",
	".output",
	".cache",
	".turbo",
	"coverage",
	"__pycache__",
	"vendor",
	"target",
	".venv",
	"venv",
]);

/**
 * 掃描目錄並列出所有路徑（用於 API 路由）
 *
 * @param {string} dirPath - 目錄路徑
 * @param {string} baseDir - 基礎路徑（用於相對計算）
 * @param {number} depth - 當前深度
 * @param {number} maxDepth - 最大深度（預設 6）
 * @returns {string[]} 路徑列表
 */
function scanPaths(dirPath, baseDir = dirPath, depth = 0, maxDepth = 6) {
	const paths = [];
	if (!fs.existsSync(dirPath) || depth > maxDepth) return paths;

	try {
		const entries = fs.readdirSync(dirPath, { withFileTypes: true });
		for (const entry of entries) {
			if (SKIP_DIRS.has(entry.name)) continue;
			const fullPath = path.join(dirPath, entry.name);
			const relPath = path.relative(baseDir, fullPath);

			if (entry.isDirectory()) {
				paths.push(...scanPaths(fullPath, baseDir, depth + 1, maxDepth));
			} else if (entry.isFile()) {
				paths.push(relPath);
			}
		}
	} catch {
		// 忽略讀取錯誤
	}

	return paths.sort();
}

/**
 * 掃描組件目錄結構（不讀取內容，只列出檔名）
 *
 * @param {string} dirPath - 目錄路徑
 * @param {number} depth - 目前深度
 * @param {number} maxDepth - 最大深度（預設 3）
 * @param {string} indent - 縮進符號
 * @returns {string[]} 樹狀結構行陣列
 */
function scanComponentTree(dirPath, depth = 0, maxDepth = 3, indent = "") {
	const lines = [];
	if (!fs.existsSync(dirPath) || depth > maxDepth) return lines;

	try {
		const entries = fs
			.readdirSync(dirPath, { withFileTypes: true })
			.sort(
				(a, b) =>
					b.isDirectory() - a.isDirectory() || a.name.localeCompare(b.name),
			);

		for (let i = 0; i < entries.length; i++) {
			const entry = entries[i];
			const isLast = i === entries.length - 1;
			const prefix = isLast ? "└── " : "├── ";
			const nextIndent = indent + (isLast ? "    " : "│   ");

			if (entry.isDirectory()) {
				lines.push(`${indent}${prefix}${entry.name}/`);
				const subDir = path.join(dirPath, entry.name);
				lines.push(
					...scanComponentTree(subDir, depth + 1, maxDepth, nextIndent),
				);
			} else {
				lines.push(`${indent}${prefix}${entry.name}`);
			}
		}
	} catch {
		// 忽略讀取錯誤
	}

	return lines;
}

/**
 * 讀取 package.json 並提取關鍵資訊
 *
 * @param {string} repoPath - repo 根目錄
 * @returns {Object} { name, scripts: [], dependencies: [] }
 */
function extractPackageInfo(repoPath) {
	const pkgPath = path.join(repoPath, "package.json");
	const info = { name: "", scripts: [], dependencies: [] };

	if (!fs.existsSync(pkgPath)) return info;

	try {
		const content = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
		info.name = content.name || "";
		info.scripts = Object.keys(content.scripts || {});
		const allDeps = {
			...content.dependencies,
			...content.devDependencies,
			...content.peerDependencies,
			...content.optionalDependencies,
		};
		info.dependencies = Object.keys(allDeps);
	} catch {
		// 忽略 JSON 解析錯誤
	}

	return info;
}

/**
 * 讀取 Prisma schema 並提取 model 定義
 *
 * @param {string} repoPath - repo 根目錄
 * @returns {Object} { models: Map<modelName, fields[]> }
 */
function extractPrismaSchema(repoPath) {
	const schemaPath = path.join(repoPath, "prisma", "schema.prisma");
	const models = new Map();

	if (!fs.existsSync(schemaPath)) return { models };

	try {
		const content = fs.readFileSync(schemaPath, "utf8");
		// 簡易正則：偵測 model 定義
		const modelRegex = /model\s+(\w+)\s*\{([^}]*)\}/gs;
		let match = modelRegex.exec(content);

		while (match !== null) {
			const modelName = match[1];
			const body = match[2];
			// 提取欄位名（簡易正則）
			const fields = [];
			const fieldRegex = /\s+(\w+)\s+\w+/g;
			let fieldMatch = fieldRegex.exec(body);
			while (fieldMatch !== null) {
				if (!fieldMatch[1].startsWith("@")) {
					fields.push(fieldMatch[1]);
				}
				fieldMatch = fieldRegex.exec(body);
			}
			if (!isEmpty(fields)) {
				models.set(modelName, fields);
			}
			match = modelRegex.exec(content);
		}
	} catch {
		// 忽略解析錯誤
	}

	return { models };
}

/**
 * 掃描 Drizzle schema 檔案
 *
 * @param {string} repoPath - repo 根目錄
 * @returns {string[]} schema 檔案列表
 */
function scanDrizzleSchemas(repoPath) {
	const files = [];
	const dirs = [
		path.join(repoPath, "drizzle"),
		path.join(repoPath, "src", "db"),
	];

	for (const dir of dirs) {
		if (fs.existsSync(dir)) {
			try {
				const entries = fs.readdirSync(dir, { withFileTypes: true });
				for (const entry of entries) {
					if (entry.isFile() && entry.name.endsWith(".ts")) {
						files.push(entry.name);
					}
				}
			} catch {
				// 忽略讀取錯誤
			}
		}
	}

	return files.sort();
}

/**
 * 掃描 src 下兩層目錄結構
 *
 * @param {string} repoPath - repo 根目錄
 * @returns {string[]} 樹狀結構行陣列
 */
function scanSourceStructure(repoPath) {
	const srcPath = path.join(repoPath, "src");
	return scanComponentTree(srcPath, 0, 1);
}

const PROJECTS_DIR = path.join(HOME, ".claude", "projects");

/**
 * 為單個 repo 生成壓縮索引
 * 部署到 ~/.claude/projects/{org}/{repo}/index/（不碰項目目錄）
 *
 * @param {string} localPath - repo 本機路徑
 * @param {string} [repoFullName] - org/repo 名（如 AlvinBian/ab-tao）
 * @returns {{ files: string[], count: number }}
 */
export function generateRepoIndex(localPath, repoFullName) {
	if (!localPath || !fs.existsSync(localPath)) {
		return { files: [], count: 0 };
	}

	// 必須提供 repoFullName，否則跳過索引生成（零污染策略）
	if (!repoFullName) {
		return { files: [], count: 0 };
	}

	let indexDir;
	try {
		// 部署到 ~/.claude/projects/{org}/{repo}/index/（不碰項目目錄）
		indexDir = path.join(PROJECTS_DIR, repoFullName, "index");
		fs.mkdirSync(indexDir, { recursive: true });
	} catch {
		return { files: [], count: 0 };
	}

	const generated = [];
	let entries;
	try {
		entries = fs.readdirSync(localPath);
	} catch {
		return { files: [], count: 0 };
	}
	const entrySet = new Set(entries);

	// 1. API routes（src/api/ 或 routes/ 或 pages/api/）
	const apiDirs = ["src/api", "routes", "pages/api"];
	for (const apiDir of apiDirs) {
		const fullPath = path.join(localPath, apiDir);
		if (fs.existsSync(fullPath)) {
			const routes = scanPaths(fullPath, fullPath);
			if (!isEmpty(routes)) {
				const content = `${INDEX_MARKER}## API Routes\n\n${routes.map((r) => `- \`${r}\``).join("\n")}\n`;
				const filePath = path.join(indexDir, "api-routes.md");
				if (
					!fs.existsSync(filePath) ||
					isGeneratedIndex(fs.readFileSync(filePath, "utf8"))
				) {
					fs.writeFileSync(filePath, content);
					generated.push("api-routes.md");
				}
			}
			break;
		}
	}

	// 2. Components（src/components/ 或 components/）
	const componentDirs = ["src/components", "components"];
	for (const compDir of componentDirs) {
		const fullPath = path.join(localPath, compDir);
		if (fs.existsSync(fullPath)) {
			const tree = scanComponentTree(fullPath);
			if (!isEmpty(tree)) {
				const content = `${INDEX_MARKER}## Component Tree\n\n\`\`\`\n${tree.join("\n")}\n\`\`\`\n`;
				const filePath = path.join(indexDir, "components.md");
				if (
					!fs.existsSync(filePath) ||
					isGeneratedIndex(fs.readFileSync(filePath, "utf8"))
				) {
					fs.writeFileSync(filePath, content);
					generated.push("components.md");
				}
			}
			break;
		}
	}

	// 3. Exports（package.json）
	if (entrySet.has("package.json")) {
		const pkgInfo = extractPackageInfo(localPath);
		if (
			pkgInfo.name ||
			!isEmpty(pkgInfo.scripts) ||
			!isEmpty(pkgInfo.dependencies)
		) {
			let content = INDEX_MARKER;
			if (pkgInfo.name) content += `## Package\n\n\`${pkgInfo.name}\`\n\n`;
			if (!isEmpty(pkgInfo.scripts)) {
				content += `## Scripts\n\n${pkgInfo.scripts.map((s) => `- \`${s}\``).join("\n")}\n\n`;
			}
			if (!isEmpty(pkgInfo.dependencies)) {
				content += `## Dependencies\n\n${pkgInfo.dependencies.map((d) => `- \`${d}\``).join("\n")}\n`;
			}
			const filePath = path.join(indexDir, "exports.md");
			if (
				!fs.existsSync(filePath) ||
				isGeneratedIndex(fs.readFileSync(filePath, "utf8"))
			) {
				fs.writeFileSync(filePath, content);
				generated.push("exports.md");
			}
		}
	}

	// 4. Schema（Prisma 或 Drizzle）
	let schemaGenerated = false;

	// Prisma
	if (entrySet.has("prisma")) {
		const prismaSchema = extractPrismaSchema(localPath);
		if (prismaSchema.models.size > 0) {
			let content = INDEX_MARKER;
			content += "## Prisma Models\n\n";
			for (const [modelName, fields] of prismaSchema.models) {
				content += `### ${modelName}\n\n${fields.map((f) => `- \`${f}\``).join("\n")}\n\n`;
			}
			const filePath = path.join(indexDir, "schema.md");
			if (
				!fs.existsSync(filePath) ||
				isGeneratedIndex(fs.readFileSync(filePath, "utf8"))
			) {
				fs.writeFileSync(filePath, content);
				generated.push("schema.md");
				schemaGenerated = true;
			}
		}
	}

	// Drizzle（如果沒有 Prisma）
	if (
		!schemaGenerated &&
		(entrySet.has("drizzle") ||
			fs.existsSync(path.join(localPath, "src", "db")))
	) {
		const drizzleSchemas = scanDrizzleSchemas(localPath);
		if (!isEmpty(drizzleSchemas)) {
			const content = `${INDEX_MARKER}## Drizzle Schemas\n\n${drizzleSchemas.map((s) => `- \`${s}\``).join("\n")}\n`;
			const filePath = path.join(indexDir, "schema.md");
			if (
				!fs.existsSync(filePath) ||
				isGeneratedIndex(fs.readFileSync(filePath, "utf8"))
			) {
				fs.writeFileSync(filePath, content);
				generated.push("schema.md");
			}
		}
	}

	// 5. Structure（src/ 下兩層）
	if (fs.existsSync(path.join(localPath, "src"))) {
		const structure = scanSourceStructure(localPath);
		if (!isEmpty(structure)) {
			const content = `${INDEX_MARKER}## Source Structure\n\n\`\`\`\nsrc/\n${structure.join("\n")}\n\`\`\`\n`;
			const filePath = path.join(indexDir, "structure.md");
			if (
				!fs.existsSync(filePath) ||
				isGeneratedIndex(fs.readFileSync(filePath, "utf8"))
			) {
				fs.writeFileSync(filePath, content);
				generated.push("structure.md");
			}
		}
	}

	return { files: generated, count: generated.length };
}

/**
 * 為所有 repos 批量生成索引
 *
 * @param {Array<{localPath: string, repo: string}>} repos - repo 列表
 * @returns {{ count: number, repos: string[] }}
 */
export function generateAllRepoIndex(repos) {
	const result = [];

	for (const { localPath, repo } of repos) {
		if (!localPath) continue;
		const indexResult = generateRepoIndex(localPath, repo);
		if (indexResult.count > 0) {
			result.push(repo);
		}
	}

	return { count: result.length, repos: result };
}
