#!/usr/bin/env node

/**
 * c:skills — Claude Skills 子命令管理（Phase 10）
 *
 * 子命令：
 *   --list                列出所有 skills 狀態
 *   --install [name...]   從 ab-tao source 安裝至 ~/.claude/skills/
 *   --update  [name...]   更新已安裝的 skill（自動 backup）
 *   --diff    <name>      顯示本地 vs source 差異
 *   --remove  <name>      安全移除（archive，不直接刪除）
 *   --find    <keyword>   從 source 搜尋 skill
 *   --from    <repo>      從 GitHub 安裝（Phase 10 後續）
 *   --global              寫入 ~/.claude/skills/（預設）
 *   --project             寫入 ./.claude/skills/（Phase 10 後續）
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ab-tao source skills 目錄（packages/commons/scripts/ → monorepo root → apps/dotfiles/claude/skills/）
const SKILLS_SOURCE = path.resolve(
	__dirname,
	"../../../apps/dotfiles/claude/skills",
);

// ~/.claude/ 路徑（從 dotfiles paths.mjs 取得，否則降級為計算值）
let P;
try {
	const dotfilePaths = await import(
		path.resolve(__dirname, "../../../apps/dotfiles/libs/core/paths.mjs")
	);
	P = dotfilePaths.P;
} catch {
	// 降級：直接計算
	const HOME = process.env.HOME || process.env.USERPROFILE || "";
	const CLAUDE = path.join(HOME, ".claude");
	P = {
		skills: path.join(CLAUDE, "skills"),
		archive: path.join(CLAUDE, "_archive"),
		agentsMd: path.join(CLAUDE, "AGENTS.md"),
	};
}

// ── 輔助函式 ────────────────────────────────────────────────────────────────

/** 掃描目錄下的第一層子資料夾（skill 名稱清單） */
function scanSkills(dir) {
	if (!fs.existsSync(dir)) return [];
	return fs
		.readdirSync(dir, { withFileTypes: true })
		.filter((e) => e.isDirectory() && !e.name.startsWith("."))
		.map((e) => e.name)
		.sort();
}

/** 讀取 SKILL.md frontmatter 中的 description */
function readSkillMeta(skillDir) {
	const skillFile = path.join(skillDir, "SKILL.md");
	if (!fs.existsSync(skillFile)) return { description: "" };
	const content = fs.readFileSync(skillFile, "utf8");
	const match = content.match(/^---\n([\s\S]*?)\n---/);
	if (!match) return { description: "" };
	const descMatch = match[1].match(/^description:\s*["']?(.+?)["']?\s*$/m);
	return { description: descMatch ? descMatch[1].trim() : "" };
}

/** 比較兩個目錄是否有差異（基於 SKILL.md）；true = 有差異 */
function hasDiff(src, dst) {
	const srcFile = path.join(src, "SKILL.md");
	const dstFile = path.join(dst, "SKILL.md");
	if (!fs.existsSync(srcFile) || !fs.existsSync(dstFile)) return true;
	try {
		execFileSync("diff", ["-q", srcFile, dstFile], { stdio: "pipe" });
		return false;
	} catch {
		return true;
	}
}

/** 生成 ~/.claude/AGENTS.md 的 <available_skills> XML 索引 */
function generateAgentsMd() {
	const skills = scanSkills(P.skills);
	if (skills.length === 0) {
		if (fs.existsSync(P.agentsMd)) fs.unlinkSync(P.agentsMd);
		return;
	}

	const entries = skills
		.map(
			(name) =>
				`  <skill name="${name}" path="${P.skills}/${name}/SKILL.md" />`,
		)
		.join("\n");

	const content = `<!-- AUTO-GENERATED by ab-tao c:skills — do not edit manually -->
<available_skills>
${entries}
</available_skills>
`;
	fs.writeFileSync(P.agentsMd, content, "utf8");
	console.log(`✅ 已更新 ~/.claude/AGENTS.md（${skills.length} 個 skills）`);
}

/** 顯示 live-reload 提示 */
function printLiveReloadHint(isNewInstall = false) {
	if (isNewInstall) {
		console.log("⚠️  新增頂層資料夾 → 需重啟 Claude Code session 才生效");
	} else {
		console.log("ℹ️  Claude Code 支援 skill 熱載入，無需重啟");
	}
}

// ── --from 輔助函式 ──────────────────────────────────────────────────────────

/**
 * 淺層 clone GitHub repo 至臨時目錄，返回 tmpDir 路徑
 * @param {string} repo  格式：owner/name
 * @returns {Promise<string>}
 */
async function cloneShallow(repo) {
	const tmpDir = await mkdtemp(path.join(tmpdir(), `ab-tao-skills-from-`));
	const url = `https://github.com/${repo}.git`;
	try {
		execFileSync("git", ["clone", "--depth", "1", url, tmpDir], {
			stdio: "pipe",
			timeout: 60000,
		});
	} catch (err) {
		await rm(tmpDir, { recursive: true, force: true });
		throw new Error(`無法 clone ${repo}：${err.message}`);
	}
	// 移除 .git 避免後續操作誤判
	fs.rmSync(path.join(tmpDir, ".git"), { recursive: true, force: true });
	return tmpDir;
}

/**
 * 掃描 skills 目錄下所有子資料夾（含 SKILL.md 者）並回傳 metadata 陣列
 * @param {string} dir  指向 skills/ 的絕對路徑
 * @returns {{ name: string, dir: string, description: string }[]}
 */
function scanSkillsDir(dir) {
	if (!fs.existsSync(dir)) return [];
	const results = [];
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (!entry.isDirectory() || entry.name.startsWith(".")) continue;
		const skillDir = path.join(dir, entry.name);
		const skillFile = path.join(skillDir, "SKILL.md");
		if (!fs.existsSync(skillFile)) continue;
		const meta = readSkillMeta(skillDir);
		results.push({
			name: entry.name,
			dir: skillDir,
			description: meta.description,
		});
	}
	return results.sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * 將 skills 安裝至 ~/.claude/skills/，記錄來源標記
 * @param {{ name: string, dir: string }[]} skills
 * @param {{ source: string }} opts
 */
function installSkillsFrom(skills, opts) {
	const skillsDirExisted = fs.existsSync(P.skills);
	if (!skillsDirExisted) {
		fs.mkdirSync(P.skills, { recursive: true });
	}

	const installed = [];
	const skipped = [];

	for (const { name, dir: src } of skills) {
		const dst = path.join(P.skills, name);
		if (fs.existsSync(dst)) {
			skipped.push(name);
			continue;
		}
		fs.cpSync(src, dst, { recursive: true });
		// 寫入來源標記
		const metaFile = path.join(dst, ".source");
		fs.writeFileSync(metaFile, opts.source, "utf8");
		installed.push(name);
	}

	if (installed.length > 0) {
		console.log(
			`\n✅ 已安裝 ${installed.length} 個 skills（來源：${opts.source}）至 ${P.skills}`,
		);
		for (const n of installed) console.log(`   + ${n}`);
		printLiveReloadHint(!skillsDirExisted);
		generateAgentsMd();
	}
	if (skipped.length > 0) {
		console.log(
			`\nℹ️  已跳過 ${skipped.length} 個（已安裝）：${skipped.join(", ")}`,
		);
		console.log("   使用 --update 更新已安裝的 skills");
	}
}

// ── 子命令實作 ───────────────────────────────────────────────────────────────

function cmdList() {
	const sourceSet = new Set(scanSkills(SKILLS_SOURCE));
	const installedSet = new Set(scanSkills(P.skills));
	const all = [...new Set([...sourceSet, ...installedSet])].sort();

	console.log(`\n📚 Skills 狀態\n`);
	console.log(`  ${"狀態".padEnd(10)}  ${"名稱".padEnd(32)}  說明`);
	console.log(`  ${"─".repeat(10)}  ${"─".repeat(32)}  ${"─".repeat(40)}`);

	for (const name of all) {
		const inSource = sourceSet.has(name);
		const installed = installedSet.has(name);

		let status;
		if (inSource && installed) {
			const diff = hasDiff(
				path.join(SKILLS_SOURCE, name),
				path.join(P.skills, name),
			);
			status = diff ? "🔄 可更新" : "✅ 最新";
		} else if (installed) {
			status = "🌐 外部";
		} else {
			status = "⬜ 未安裝";
		}

		const meta = inSource
			? readSkillMeta(path.join(SKILLS_SOURCE, name))
			: readSkillMeta(path.join(P.skills, name));

		const desc = meta.description.slice(0, 48);
		console.log(`  ${status.padEnd(10)}  ${name.padEnd(32)}  ${desc}`);
	}
	console.log(`\n  source: ${SKILLS_SOURCE}`);
	console.log(`  target: ${P.skills}\n`);
}

function cmdInstall(names) {
	const sourceSkills = scanSkills(SKILLS_SOURCE);
	const toInstall = names.length > 0 ? names : sourceSkills;
	const skillsDirExisted = fs.existsSync(P.skills);

	if (!skillsDirExisted) {
		fs.mkdirSync(P.skills, { recursive: true });
	}

	const installed = [];
	const skipped = [];
	const notFound = [];

	for (const name of toInstall) {
		const src = path.join(SKILLS_SOURCE, name);
		const dst = path.join(P.skills, name);

		if (!fs.existsSync(src)) {
			notFound.push(name);
			continue;
		}
		if (fs.existsSync(dst)) {
			skipped.push(name);
			continue;
		}

		fs.cpSync(src, dst, { recursive: true });
		installed.push(name);
	}

	if (installed.length > 0) {
		console.log(`\n✅ 已安裝 ${installed.length} 個 skills 至 ${P.skills}`);
		for (const n of installed) console.log(`   + ${n}`);
		printLiveReloadHint(!skillsDirExisted);
		generateAgentsMd();
	}
	if (skipped.length > 0) {
		console.log(
			`\nℹ️  已跳過 ${skipped.length} 個（已安裝）：${skipped.join(", ")}`,
		);
		console.log("   使用 --update 更新已安裝的 skills");
	}
	if (notFound.length > 0) {
		console.error(`\n❌ source 中找不到：${notFound.join(", ")}`);
		console.error(`   可用 skills：${sourceSkills.join(", ")}`);
		process.exitCode = 1;
	}
}

function cmdUpdate(names) {
	const sourceSkills = scanSkills(SKILLS_SOURCE);
	const installedSkills = scanSkills(P.skills);
	const candidates =
		names.length > 0
			? names
			: installedSkills.filter((n) => sourceSkills.includes(n));

	const updated = [];
	const upToDate = [];
	const notFound = [];

	for (const name of candidates) {
		const src = path.join(SKILLS_SOURCE, name);
		const dst = path.join(P.skills, name);

		if (!fs.existsSync(src)) {
			notFound.push(name);
			continue;
		}
		if (!fs.existsSync(dst)) {
			fs.cpSync(src, dst, { recursive: true });
			updated.push(`${name} (新安裝)`);
			continue;
		}

		if (!hasDiff(src, dst)) {
			upToDate.push(name);
			continue;
		}

		// Backup 舊版本
		const backupDir = `${dst}.bak.${Date.now()}`;
		fs.cpSync(dst, backupDir, { recursive: true });
		fs.rmSync(dst, { recursive: true });
		fs.cpSync(src, dst, { recursive: true });
		updated.push(name);
	}

	if (updated.length > 0) {
		console.log(`\n✅ 已更新 ${updated.length} 個 skills`);
		for (const n of updated) console.log(`   ↑ ${n}`);
		printLiveReloadHint(false);
		generateAgentsMd();
	}
	if (upToDate.length > 0) {
		console.log(`\nℹ️  ${upToDate.length} 個已是最新版：${upToDate.join(", ")}`);
	}
	if (notFound.length > 0) {
		console.error(`\n❌ source 中找不到：${notFound.join(", ")}`);
		process.exitCode = 1;
	}
}

function cmdDiff(name) {
	if (!name) {
		console.error("❌ 請指定 skill 名稱：c:skills --diff <name>");
		process.exit(1);
	}

	const srcFile = path.join(SKILLS_SOURCE, name, "SKILL.md");
	const dstFile = path.join(P.skills, name, "SKILL.md");

	if (!fs.existsSync(srcFile)) {
		console.error(`❌ source 中找不到 ${name}`);
		process.exit(1);
	}
	if (!fs.existsSync(dstFile)) {
		console.log(`ℹ️  ${name} 尚未安裝（使用 --install ${name}）`);
		return;
	}

	try {
		execFileSync("diff", ["-q", srcFile, dstFile], { stdio: "pipe" });
		console.log(`✅ ${name}：本地與 source 一致，無需更新`);
	} catch (e) {
		const diffOutput = /** @type {string} */ (e.stdout ?? "");
		if (diffOutput) {
			console.log(`--- 本地  ${dstFile}`);
			console.log(`+++ source ${srcFile}\n`);
			// 使用 diff -u 取得 unified diff
			try {
				execFileSync("diff", ["-u", dstFile, srcFile], { stdio: "inherit" });
			} catch {
				// diff 回傳 exit 1 表示有差異，非錯誤
			}
		} else {
			console.log(
				`🔄 ${name}：SKILL.md 有差異（執行 --update ${name} 可更新）`,
			);
		}
	}
}

function cmdRemove(name) {
	if (!name) {
		console.error("❌ 請指定 skill 名稱：c:skills --remove <name>");
		process.exit(1);
	}

	const dst = path.join(P.skills, name);
	if (!fs.existsSync(dst)) {
		console.error(`❌ ${name} 未安裝`);
		process.exit(1);
	}

	// Archive-not-delete（O5 原則）
	const archiveDir = path.join(P.archive, `skills-removed-${Date.now()}`);
	fs.mkdirSync(archiveDir, { recursive: true });
	fs.cpSync(dst, path.join(archiveDir, name), { recursive: true });
	fs.rmSync(dst, { recursive: true });

	console.log(`✅ 已移除 ${name}（備份至 ${archiveDir}）`);
	generateAgentsMd();
}

function cmdFind(keyword) {
	if (!keyword) {
		console.error("❌ 請指定關鍵字：c:skills --find <keyword>");
		process.exit(1);
	}

	const sourceSkills = scanSkills(SKILLS_SOURCE);
	const kw = keyword.toLowerCase();
	const results = [];

	for (const name of sourceSkills) {
		const meta = readSkillMeta(path.join(SKILLS_SOURCE, name));
		if (
			name.toLowerCase().includes(kw) ||
			meta.description.toLowerCase().includes(kw)
		) {
			results.push({ name, description: meta.description });
		}
	}

	if (results.length === 0) {
		console.log(`ℹ️  找不到包含「${keyword}」的 skill`);
		return;
	}

	console.log(`\n🔍 搜尋「${keyword}」結果（${results.length} 個）：\n`);
	for (const { name, description } of results) {
		console.log(`  ${name}`);
		if (description) console.log(`    ${description}`);
	}
	console.log();
}

// ── 主 dispatch ──────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const [flag, ...rest] = args;

switch (flag) {
	case undefined:
	case "--list":
		cmdList();
		break;
	case "--install":
		cmdInstall(rest);
		break;
	case "--update":
		cmdUpdate(rest);
		break;
	case "--diff":
		cmdDiff(rest[0]);
		break;
	case "--remove":
		cmdRemove(rest[0]);
		break;
	case "--find":
		cmdFind(rest[0]);
		break;
	case "--from": {
		// --from <repo> [--find <keyword>]
		const repo = rest[0];
		if (!repo) {
			console.error("❌ --from 需要指定 repo（格式：owner/name）");
			process.exit(1);
		}
		const findIdx = rest.indexOf("--find");
		const keyword = findIdx !== -1 ? rest[findIdx + 1] : null;

		console.log(`\n正在從 github:${repo} 取得 skills…`);
		let tmpDir;
		try {
			tmpDir = await cloneShallow(repo);
		} catch (err) {
			console.error(`❌ ${err.message}`);
			process.exit(1);
		}

		const skillsPath = path.join(tmpDir, "skills");
		if (!fs.existsSync(skillsPath)) {
			console.error(`❌ ${repo} 中找不到 skills/ 目錄`);
			await rm(tmpDir, { recursive: true, force: true });
			process.exit(1);
		}

		let skills = scanSkillsDir(skillsPath);

		if (keyword) {
			// 過濾關鍵字
			const kw = keyword.toLowerCase();
			skills = skills.filter(
				(s) =>
					s.name.toLowerCase().includes(kw) ||
					s.description.toLowerCase().includes(kw),
			);
			if (skills.length === 0) {
				console.log(`ℹ️  ${repo} 中找不到包含「${keyword}」的 skill`);
				await rm(tmpDir, { recursive: true, force: true });
				process.exit(0);
			}
			console.log(`\n🔍 搜尋「${keyword}」結果（${skills.length} 個）：\n`);
			for (const { name, description } of skills) {
				console.log(`  ${name}`);
				if (description) console.log(`    ${description}`);
			}
			console.log();
		}

		installSkillsFrom(skills, { source: `github:${repo}` });
		await rm(tmpDir, { recursive: true, force: true });
		break;
	}
	case "--global":
		console.log("ℹ️  --global 是預設行為（寫入 ~/.claude/skills/）。");
		cmdList();
		break;
	case "--project":
		console.log("ℹ️  --project（寫入 ./.claude/skills/）規劃於後續版本。");
		break;
	default:
		console.error(`❌ 未知旗標：${flag}`);
		console.error(
			"用法：c:skills [--list|--install|--update|--diff|--remove|--find] [name]",
		);
		process.exit(1);
}
