import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, it } from "node:test";
import {
	generateAllRepoIndex,
	generateRepoIndex,
} from "../lib/deploy/deploy-index.mjs";

describe("generateRepoIndex", () => {
	let tmpDir;

	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "repo-index-test-"));
	});

	afterEach(() => {
		fs.rmSync(tmpDir, { recursive: true, force: true });
	});

	it("對不存在的路徑返回空結果", () => {
		const result = generateRepoIndex("/nonexistent/path");
		assert.deepEqual(result, { files: [], count: 0 });
	});

	it("對空目錄返回空結果", () => {
		const result = generateRepoIndex(tmpDir);
		assert.deepEqual(result, { files: [], count: 0 });
	});

	it("對有 package.json 的目錄生成 exports.md", () => {
		// 建立 package.json
		const pkgJson = {
			name: "@test/my-package",
			scripts: {
				build: "tsc",
				test: "node --test",
			},
			dependencies: {
				lodash: "^4.17.0",
			},
			devDependencies: {
				typescript: "^5.0.0",
			},
		};
		fs.writeFileSync(
			path.join(tmpDir, "package.json"),
			JSON.stringify(pkgJson, null, 2),
		);

		const result = generateRepoIndex(tmpDir);
		assert.ok(result.files.includes("exports.md"));
		assert.equal(result.count, 1);

		// 驗證生成的內容
		const indexDir = path.join(tmpDir, ".claude", "index");
		assert.ok(fs.existsSync(indexDir));
		const exportsPath = path.join(indexDir, "exports.md");
		assert.ok(fs.existsSync(exportsPath));
		const content = fs.readFileSync(exportsPath, "utf8");
		assert.ok(content.startsWith("# Generated by ab-tao"));
		assert.ok(content.includes("@test/my-package"));
		assert.ok(content.includes("build"));
		assert.ok(content.includes("lodash"));
	});

	it("對有 src/ 的目錄生成 structure.md", () => {
		// 建立 src 結構
		fs.mkdirSync(path.join(tmpDir, "src", "utils"), { recursive: true });
		fs.mkdirSync(path.join(tmpDir, "src", "components"), { recursive: true });
		fs.writeFileSync(path.join(tmpDir, "src", "utils", "helpers.ts"), "");
		fs.writeFileSync(path.join(tmpDir, "src", "components", "Button.tsx"), "");

		const result = generateRepoIndex(tmpDir);
		assert.ok(result.files.includes("structure.md"));

		// 驗證生成的內容
		const structPath = path.join(tmpDir, ".claude", "index", "structure.md");
		assert.ok(fs.existsSync(structPath));
		const content = fs.readFileSync(structPath, "utf8");
		assert.ok(content.includes("## Source Structure"));
		assert.ok(content.includes("utils"));
		assert.ok(content.includes("components"));
	});

	it("不覆蓋用戶自訂的索引文件（無 marker）", () => {
		// 建立 package.json
		fs.writeFileSync(
			path.join(tmpDir, "package.json"),
			JSON.stringify({ name: "test" }),
		);

		// 建立用戶自訂的 exports.md（無 marker）
		const indexDir = path.join(tmpDir, ".claude", "index");
		fs.mkdirSync(indexDir, { recursive: true });
		const userContent = "# 我的自訂索引\n\n自定義內容";
		fs.writeFileSync(path.join(indexDir, "exports.md"), userContent);

		const result = generateRepoIndex(tmpDir);
		// 不應覆蓋用戶自訂的文件
		assert.ok(!result.files.includes("exports.md"));

		// 驗證內容保持不變
		const content = fs.readFileSync(path.join(indexDir, "exports.md"), "utf8");
		assert.equal(content, userContent);
	});

	it("覆蓋先前自動生成的索引文件（有 marker）", () => {
		// 建立 package.json
		const newPkg = { name: "updated-package", scripts: { lint: "eslint" } };
		fs.writeFileSync(path.join(tmpDir, "package.json"), JSON.stringify(newPkg));

		// 建立舊的自動生成文件
		const indexDir = path.join(tmpDir, ".claude", "index");
		fs.mkdirSync(indexDir, { recursive: true });
		const oldContent = "# Generated by ab-tao — repo index\n\n舊內容";
		fs.writeFileSync(path.join(indexDir, "exports.md"), oldContent);

		const result = generateRepoIndex(tmpDir);
		assert.ok(result.files.includes("exports.md"));

		// 驗證內容已更新
		const content = fs.readFileSync(path.join(indexDir, "exports.md"), "utf8");
		assert.ok(content.includes("updated-package"));
		assert.ok(content.includes("lint"));
	});

	it("對有 Prisma schema 的目錄生成 schema.md", () => {
		// 建立 Prisma schema
		fs.mkdirSync(path.join(tmpDir, "prisma"));
		const schema = `
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  posts Post[]
}

model Post {
  id    Int     @id @default(autoincrement())
  title String
  userId Int
}
`;
		fs.writeFileSync(path.join(tmpDir, "prisma", "schema.prisma"), schema);

		const result = generateRepoIndex(tmpDir);
		assert.ok(result.files.includes("schema.md"));

		const schemaPath = path.join(tmpDir, ".claude", "index", "schema.md");
		const content = fs.readFileSync(schemaPath, "utf8");
		assert.ok(content.includes("## Prisma Models"));
		assert.ok(content.includes("User"));
		assert.ok(content.includes("Post"));
	});

	it("對有 API 路由的目錄生成 api-routes.md", () => {
		// 建立 src/api 結構
		fs.mkdirSync(path.join(tmpDir, "src", "api", "users"), { recursive: true });
		fs.mkdirSync(path.join(tmpDir, "src", "api", "posts"), { recursive: true });
		fs.writeFileSync(path.join(tmpDir, "src", "api", "users", "[id].ts"), "");
		fs.writeFileSync(path.join(tmpDir, "src", "api", "posts", "index.ts"), "");

		const result = generateRepoIndex(tmpDir);
		assert.ok(result.files.includes("api-routes.md"));

		const routesPath = path.join(tmpDir, ".claude", "index", "api-routes.md");
		const content = fs.readFileSync(routesPath, "utf8");
		assert.ok(content.includes("## API Routes"));
		assert.ok(content.includes("[id].ts"));
		assert.ok(content.includes("index.ts"));
	});
});

describe("generateAllRepoIndex", () => {
	let tmpDir1;
	let tmpDir2;

	beforeEach(() => {
		tmpDir1 = fs.mkdtempSync(path.join(os.tmpdir(), "repo-index-all-1-"));
		tmpDir2 = fs.mkdtempSync(path.join(os.tmpdir(), "repo-index-all-2-"));
	});

	afterEach(() => {
		fs.rmSync(tmpDir1, { recursive: true, force: true });
		fs.rmSync(tmpDir2, { recursive: true, force: true });
	});

	it("批量處理多個 repos 並返回統計", () => {
		// 為第一個 repo 建立 package.json
		fs.writeFileSync(
			path.join(tmpDir1, "package.json"),
			JSON.stringify({ name: "repo1" }),
		);

		// 為第二個 repo 建立 src 結構
		fs.mkdirSync(path.join(tmpDir2, "src"));
		fs.writeFileSync(path.join(tmpDir2, "src", "index.ts"), "");

		const repos = [
			{ localPath: tmpDir1, repo: "org/repo1" },
			{ localPath: tmpDir2, repo: "org/repo2" },
		];

		const result = generateAllRepoIndex(repos);
		assert.equal(result.count, 2);
		assert.deepEqual(result.repos, ["org/repo1", "org/repo2"]);
	});

	it("跳過沒有可生成內容的 repos", () => {
		// tmpDir1 保持空
		// 為第二個 repo 建立內容
		fs.writeFileSync(
			path.join(tmpDir2, "package.json"),
			JSON.stringify({ name: "repo2" }),
		);

		const repos = [
			{ localPath: tmpDir1, repo: "org/repo1" },
			{ localPath: tmpDir2, repo: "org/repo2" },
		];

		const result = generateAllRepoIndex(repos);
		assert.equal(result.count, 1);
		assert.deepEqual(result.repos, ["org/repo2"]);
	});

	it("處理沒有 localPath 的 repos", () => {
		// 為第一個 repo 建立內容
		fs.writeFileSync(
			path.join(tmpDir1, "package.json"),
			JSON.stringify({ name: "repo1" }),
		);

		const repos = [
			{ localPath: tmpDir1, repo: "org/repo1" },
			{ localPath: "", repo: "org/repo2" },
			{ localPath: null, repo: "org/repo3" },
		];

		const result = generateAllRepoIndex(repos);
		assert.equal(result.count, 1);
		assert.deepEqual(result.repos, ["org/repo1"]);
	});
});
