import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, it } from "node:test";
import { deployClaudeignore } from "../lib/deploy/deploy-project.mjs";

describe("deployClaudeignore", () => {
	let tmpDir;

	beforeEach(() => {
		tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "claudeignore-test-"));
	});

	afterEach(() => {
		fs.rmSync(tmpDir, { recursive: true, force: true });
	});

	it("對不存在的路徑返回 false", () => {
		const result = deployClaudeignore("/nonexistent/path");
		assert.equal(result, false);
	});

	it("對有 node_modules 的目錄生成包含 node_modules/ 的 .claudeignore", () => {
		// 建立 node_modules
		fs.mkdirSync(path.join(tmpDir, "node_modules"));

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		// 驗證 .claudeignore 已生成
		const ignorePath = path.join(tmpDir, ".claudeignore");
		assert.ok(fs.existsSync(ignorePath));

		// 驗證內容包含 node_modules/
		const content = fs.readFileSync(ignorePath, "utf8");
		assert.ok(content.includes("node_modules/"));
		assert.ok(content.startsWith("# Generated by ab-tao"));
	});

	it("對有 .next 的目錄生成包含 .next/ 的 .claudeignore", () => {
		// 建立 .next（Next.js 構建產物）
		fs.mkdirSync(path.join(tmpDir, ".next"));

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes(".next/"));
	});

	it("對有 dist 和 node_modules 的目錄同時生成兩個規則", () => {
		// 建立多個需要忽略的目錄
		fs.mkdirSync(path.join(tmpDir, "dist"));
		fs.mkdirSync(path.join(tmpDir, "node_modules"));

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes("dist/"));
		assert.ok(content.includes("node_modules/"));
	});

	it("不覆蓋用戶自訂的 .claudeignore（無 marker）", () => {
		// 建立 node_modules
		fs.mkdirSync(path.join(tmpDir, "node_modules"));

		// 建立用戶自訂的 .claudeignore（無 marker）
		const userContent = "# 我的自訂 .claudeignore\n\nmy-custom-rule/";
		fs.writeFileSync(path.join(tmpDir, ".claudeignore"), userContent);

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, false);

		// 驗證內容保持不變
		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.equal(content, userContent);
	});

	it("覆蓋先前自動生成的 .claudeignore（有 marker）", () => {
		// 建立新的 package-lock.json
		fs.writeFileSync(path.join(tmpDir, "package-lock.json"), "");

		// 建立舊的自動生成 .claudeignore（有 marker，但不同內容）
		const oldContent = "# Generated by ab-tao\nnode_modules/\n";
		fs.writeFileSync(path.join(tmpDir, ".claudeignore"), oldContent);

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		// 驗證內容已更新
		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes("package-lock.json"));
	});

	it("對沒有可忽略內容的目錄返回 false", () => {
		// 建立一個只有 .md 檔案的目錄
		fs.writeFileSync(path.join(tmpDir, "README.md"), "# 空專案");

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, false);

		// .claudeignore 不應被建立
		const ignorePath = path.join(tmpDir, ".claudeignore");
		assert.ok(!fs.existsSync(ignorePath));
	});

	it("對有 pnpm-lock.yaml 的目錄生成包含該規則", () => {
		// 建立 pnpm-lock.yaml
		fs.writeFileSync(path.join(tmpDir, "pnpm-lock.yaml"), "");

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes("pnpm-lock.yaml"));
	});

	it("對有 .csproj（.NET 專案）的目錄生成包含 bin/ 和 obj/", () => {
		// 建立 .csproj 檔案
		fs.writeFileSync(path.join(tmpDir, "MyProject.csproj"), "");

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes("bin/") || content.includes("obj/"));
	});

	it("對有 Cargo.toml（Rust 專案）的目錄生成包含 target/", () => {
		// 建立 Cargo.toml
		fs.writeFileSync(path.join(tmpDir, "Cargo.toml"), "");

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes("target/"));
	});

	it("對有 pyproject.toml（Python 專案）的目錄生成包含 __pycache__ 和 .mypy_cache", () => {
		// 建立 pyproject.toml
		fs.writeFileSync(path.join(tmpDir, "pyproject.toml"), "");

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(
			content.includes("__pycache__/") ||
				content.includes("*.pyc") ||
				content.includes(".mypy_cache/"),
		);
	});

	it("對有多個鎖檔的目錄只保留匹配的規則", () => {
		// 建立 yarn.lock
		fs.writeFileSync(path.join(tmpDir, "yarn.lock"), "");

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes("yarn.lock"));
		// 不應包含 pnpm-lock 或 package-lock
		assert.ok(!content.includes("pnpm-lock"));
		assert.ok(!content.includes("package-lock"));
	});

	it("生成的 .claudeignore 包含減少 token 消耗的註釋", () => {
		// 建立 node_modules
		fs.mkdirSync(path.join(tmpDir, "node_modules"));

		deployClaudeignore(tmpDir);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes("— 減少 Claude Code 掃描的 token 消耗"));
	});

	it("對有 git 目錄的專案生成包含 .git/", () => {
		// 建立 .git 目錄
		fs.mkdirSync(path.join(tmpDir, ".git"));

		const result = deployClaudeignore(tmpDir);
		assert.equal(result, true);

		const content = fs.readFileSync(path.join(tmpDir, ".claudeignore"), "utf8");
		assert.ok(content.includes(".git/"));
	});
});
